name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build iOS App
      run: npx react-native run-ios --configuration Release
    - name: Archive App
      run: xcodebuild -workspace NomeDoSeuProjeto.xcworkspace -scheme NomeDoSeuProjeto -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/NomeDoSeuProjeto.xcarchive
    - name: Export IPA
      run: xcodebuild -exportArchive -archivePath $PWD/build/NomeDoSeuProjeto.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build
